apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ssm-store
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: kube-system
      region: us-east-1
      service: ParameterStore
