apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1f
- us-east-1b
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  disableIMDSv1: true
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: true
      appMeshPreview: false
      autoScaler: true
      certManager: true
      cloudWatch: true
      ebs: true
      efs: true
      externalDNS: true
      fsx: false
      imageBuilder: true
      xRay: false
  instanceSelector: {}
  instanceType: t3.small
  labels:
    alpha.eksctl.io/cluster-name: aws101
    alpha.eksctl.io/nodegroup-name: aws101-nodes
  maxSize: 1
  minSize: 1
  name: aws101-nodes
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
    enableSsm: false
    publicKeyPath: ""
  tags:
    alpha.eksctl.io/nodegroup-name: aws101-nodes
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 50
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: aws101
  region: us-east-1
  tags:
    environment: aws101
    owner: damian
    project: aws101
  version: "1.21"
privateCluster:
  enabled: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
