apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-shared-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: efs-app
  template:
    metadata:
      labels:
        app: efs-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        - name: logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: efs-claim
      - name: logs
        persistentVolumeClaim:
          claimName: efs-claim
