apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: staging
  labels:
    app: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  replicas: 1
  template:
    metadata:
      labels:
        app: external-dns
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::ACCOUNT_ID:role/eksctl-staging-addon-iamserviceaccount-Role
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.0
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=staging.example.com
        - --provider=aws
        - --policy=sync
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id=staging-cluster
        - --txt-prefix=staging-
        - --log-level=debug
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      serviceAccount: external-dns
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
