apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: student-test
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: test
      containers:
      - name: my-app
        image: nginx
