apiVersion: v1
kind: Pod
metadata:
  name: s3-reader-pod
  namespace: default
spec:
  serviceAccountName: s3-reader-podidentity
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ["sleep", "3600"]
    env:
    - name: AWS_REGION
      value: "us-east-1"
  restartPolicy: Never
