apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://E2C8057A6AF8CA7AFC3D72B2C2358B87.gr7.us-east-1.eks.amazonaws.com
    insecure-skip-tls-verify: true
  name: eks-cluster
contexts:
- context:
    cluster: eks-cluster
    namespace: student-test
    user: test
  name: student-context
current-context: student-context
users:
- name: test
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjF3UXRaVEJzeUVXSXhmVVcwRi1nWkQxdGNUUGdLNkFFTGJhNnExVjBVdTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdHVkZW50LXRlc3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoidGVzdC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ0ZXN0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjhlYTE3ZWQtNDQ4OS00MTQ4LThhOWUtZGYxYmJiMjY0YzA5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN0dWRlbnQtdGVzdDp0ZXN0In0.gzbb_AH35c7fDJLPm-7SNWA3AeJqInR3YxtqhzfMc60dmYEhhaiVsj9apOvBlAnyOZa99lht5PG8Sq41wHx-OwmG_gtlWjMXn3o4jbt22MtD83fgvI3Zscp64zscdyVL2WZJpdXHByFMLB-MioowE_zdqh7WvGf-Q1V6vHa1rIj0ubdSCpiA_th1ZR2r7BKQxNGrL4HNNcSYy0tK2qkoAG9n48idClJOcV1dhK938nfqtPEJz0CaOaL02pNmkxBua4pwWnaPAb7dTmVtUeLulWTWzfLnE96k6GxEa-81_PdGIiy1f9F6YpeT5oE4CwadligRFG3bhzXCqG2qSZ-2rw
