{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-external-secret
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-secret
    creationPolicy: Owner
  data:
  - secretKey: database-password
    remoteRef:
      key: {{ .Values.externalSecret.secretKey }}
{{- end }}
