apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: clase15
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mariadb
