apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efs-demo
  template:
    metadata:
      labels:
        app: efs-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-storage
          mountPath: /usr/share/nginx/html
        - name: efs-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "<h1>Pod: $HOSTNAME</h1>" > /usr/share/nginx/html/index.html
                echo "<p>Shared EFS Storage Working!</p>" >> /usr/share/nginx/html/index.html
                echo "<p>Generated at: $(date)</p>" >> /usr/share/nginx/html/index.html
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim
      - name: efs-logs
        persistentVolumeClaim:
          claimName: efs-claim
